version: '3'
services: MongoDB
  app: 
    build: .
    ports: "3000:3000"
    depends_on: 
      - MongoDB
    environment:
      - MONGODB_URI = "mongodb://mongodb:27017/project"
    MongoDB:
      image: mongo
      ports:
        - 27017:27017
      volumes: 
        - .:/app
      
  mongo: 
    image: mongo
    ports: 
      - 27017:27017
    container_name: mongo
    volumes:
      - mongo-data:/data/db
      
  volumes: 
    mongo-data: